# Config to match the Llama-3.1-8B model pre-training experiments from https://github.com/facebookresearch/lingua.

defaults:
  - defaults
  - _self_

config_name_or_path: ./model_configs/meta-llama/Llama-3.1-8B

config_kwargs:
  attn_input_format: thd

use_sequence_packing: true

# FP32 master weights via TE FusedAdam (recommended over MixedPrecisionPolicy)
use_fp32_master_weights: true

wandb:
  name: lingua-8b-bf16
  project: lingua-8b
  id: lingua-8b-bf16

num_train_steps: 60_000

dataset:
  tokenizer_name_or_path: ./tokenizers/Meta-Llama-3-8B
  micro_batch_size: 2
  num_workers: 8
  max_seq_length: 8192
  stride: 512
  buffer_size: 10_000
  use_stateful_dataloader: false
  mask_degenerate_bases: false
  uppercase_labels: false
  load_dataset_kwargs:
    path: parquet
    data_files: "/workspace/data/dclm-baseline/global-shard_01_of_10/**/*.parquet"
    split: "train"
    streaming: true

grad_acc_steps: 4            # GBS = 2 * 4 * 32 GPUs = 256 (4 nodes)

adamw_kwargs:
  lr: 3e-4
  fused: true
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 0.01

lr_scheduler_kwargs:
  num_warmup_steps: 5_000
  num_decay_steps: 55_000 # total_steps - num_warmup_steps = 60_000 - 5_000
  min_lr_ratio: 0.000001

# Checkpoint config
checkpoint:
  ckpt_dir: null
  save_final_model: true
  resume_from_checkpoint: true
  save_every_n_steps: 10_000
  async_save: false

profiler:
  enabled: false
